version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: guestlink-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: guestlink
    volumes:
      - guestlink-db-data:/var/lib/postgresql/data
    restart: always

volumes:
  guestlink-db-data:
